# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-31 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackOkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_info',
            field=models.TextField(null=True),
        ),
    ]
