# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-31 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackOkapp', '0002_auto_20180831_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
