# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-31 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackOkapp', '0003_auto_20180831_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='contact',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
