# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackOkapp', '0004_child_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='child',
            name='child_pic',
            field=models.ImageField(default='HackOkapp/pic_folder/None/no-img.jpg', upload_to='HackOkPlease/pic_folder/'),
        ),
    ]
