# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HackOkapp', '0005_auto_20181026_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_pic', models.ImageField(default='HackOkapp/pic_folder/None/no-img.jpg', upload_to='HackOkPlease/pic_folder/')),
            ],
        ),
    ]
