# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HackOkapp', '0006_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='location',
        ),
    ]
