# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HackOkapp', '0007_auto_20190419_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
